version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: jessemillar/arch-renpy-build:latest
    steps:
      - checkout
      # - run:
          # name: Lint with Ren'Py
          # command: renutil launch $(renutil list) lint .
      - run:
          name: Build with Ren'Py
          command: renutil launch $(renutil list) distribute .
      - run:
          name: "Publish Release on GitHub and itch.io"
          command: |
            VERSION=$(grep config.version < ./game/options.rpy | cut -d'"' -f2)
            cd "./$CIRCLE_PROJECT_REPONAME-$VERSION-dists" || exit
            ghr -t "${GITHUB_TOKEN}" -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" -n "v${VERSION}" -delete "v${VERSION}" .
            WIN_FILE=$(ls ./*-win.zip); butler push "$WIN_FILE" "compycore/${CIRCLE_PROJECT_REPONAME}:windows" --userversion "$VERSION"
            MACOS_FILE=$(ls ./*-mac.zip); butler push "$MACOS_FILE" "compycore/${CIRCLE_PROJECT_REPONAME}:macos" --userversion "$VERSION"
            LINUX_FILE=$(ls ./*-linux.tar.bz2); butler push "$LINUX_FILE" "compycore/${CIRCLE_PROJECT_REPONAME}:linux" --userversion "$VERSION"
